package com.ironforge.backend.service;

import com.ironforge.backend.domain.membership.Member;
import com.ironforge.backend.domain.membership.Subscription;
import com.ironforge.backend.domain.membership.SubscriptionPlan;
import com.ironforge.backend.domain.membership.enums.PaymentMethod;
import com.ironforge.backend.domain.membership.valueobject.Email;
import com.ironforge.backend.domain.membership.valueobject.Money;
import com.ironforge.backend.domain.membership.valueobject.PhoneNumber;
import com.ironforge.backend.dto.subscription.SubscriptionInsertDTO;
import com.ironforge.backend.dto.subscription.SubscriptionReadOnlyDTO;
import com.ironforge.backend.exception.EntityAlreadyExistsException;
import com.ironforge.backend.exception.EntityNotFoundException;
import com.ironforge.backend.exception.InvalidRequestException;
import com.ironforge.backend.mapper.Mapper;
import com.ironforge.backend.repository.MemberRepository;
import com.ironforge.backend.repository.PaymentRepository;
import com.ironforge.backend.repository.SubscriptionPlanRepository;
import com.ironforge.backend.repository.SubscriptionRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.argThat;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.verifyNoInteractions;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
class SubscriptionServiceImplTest {

    @Mock private SubscriptionRepository subscriptionRepository;
    @Mock private MemberRepository memberRepository;
    @Mock private SubscriptionPlanRepository subscriptionPlanRepository;
    @Mock private PaymentRepository paymentRepository;

    private final Mapper mapper = new Mapper();

    private SubscriptionServiceImpl subscriptionService;

    private Member member;
    private SubscriptionPlan activePlan;

    @BeforeEach
    void setUp() {
        subscriptionService = new SubscriptionServiceImpl(
                subscriptionRepository, memberRepository, subscriptionPlanRepository, paymentRepository, mapper);

        member = new Member();
        member.setId(1L);
        member.setFirstName("Giorgos");
        member.setLastName("Papadopoulos");
        member.setEmail(new Email("giorgos@example.com"));
        member.setPhoneNumber(new PhoneNumber("6912345678"));

        activePlan = new SubscriptionPlan();
        activePlan.setId(10L);
        activePlan.setName("Monthly");
        activePlan.setDurationDays(30);
        activePlan.setPrice(new Money(BigDecimal.valueOf(25), "EUR"));
        activePlan.setActive(true);
    }

    @Test
    void createSubscription_createsSubscriptionAndAutoGeneratedPaymentTogether() {
        SubscriptionInsertDTO dto = new SubscriptionInsertDTO(1L, 10L, PaymentMethod.CASH);

        when(memberRepository.findByIdAndDeletedFalse(1L)).thenReturn(Optional.of(member));
        when(subscriptionPlanRepository.findById(10L)).thenReturn(Optional.of(activePlan));
        when(subscriptionRepository.existsByMember_IdAndEndDateGreaterThanEqual(eq(1L), any(LocalDate.class)))
                .thenReturn(false);
        when(subscriptionRepository.save(any(Subscription.class))).thenAnswer(invocation -> {
            Subscription saved = invocation.getArgument(0);
            saved.setId(100L);
            return saved;
        });

        SubscriptionReadOnlyDTO result = subscriptionService.createSubscription(dto);

        assertThat(result.id()).isEqualTo(100L);
        assertThat(result.planName()).isEqualTo("Monthly");
        assertThat(result.endDate()).isEqualTo(LocalDate.now().plusDays(30));

        // the business rule under test: a Payment must be created as a side-effect of
        // creating the Subscription, in the same call, with no separate API step
        verify(paymentRepository).save(argThat(payment ->
                payment.getAmount().getAmount().compareTo(BigDecimal.valueOf(25).setScale(2)) == 0
                        && payment.getMethod() == PaymentMethod.CASH
                        && payment.getSubscription().getId().equals(100L)
                        && payment.getMember().getId().equals(1L)
        ));
    }

    @Test
    void createSubscription_rejectsAnInactivePlan() {
        activePlan.setActive(false);
        SubscriptionInsertDTO dto = new SubscriptionInsertDTO(1L, 10L, PaymentMethod.CASH);

        when(memberRepository.findByIdAndDeletedFalse(1L)).thenReturn(Optional.of(member));
        when(subscriptionPlanRepository.findById(10L)).thenReturn(Optional.of(activePlan));

        assertThatThrownBy(() -> subscriptionService.createSubscription(dto))
                .isInstanceOf(InvalidRequestException.class);

        verifyNoInteractions(paymentRepository);
        verify(subscriptionRepository, never()).save(any());
    }

    @Test
    void createSubscription_rejectsWhenMemberAlreadyHasAnActiveSubscription() {
        SubscriptionInsertDTO dto = new SubscriptionInsertDTO(1L, 10L, PaymentMethod.CASH);

        when(memberRepository.findByIdAndDeletedFalse(1L)).thenReturn(Optional.of(member));
        when(subscriptionPlanRepository.findById(10L)).thenReturn(Optional.of(activePlan));
        when(subscriptionRepository.existsByMember_IdAndEndDateGreaterThanEqual(eq(1L), any(LocalDate.class)))
                .thenReturn(true);

        assertThatThrownBy(() -> subscriptionService.createSubscription(dto))
                .isInstanceOf(EntityAlreadyExistsException.class);

        verifyNoInteractions(paymentRepository);
        verify(subscriptionRepository, never()).save(any());
    }

    @Test
    void createSubscription_throwsNotFound_whenMemberDoesNotExist() {
        SubscriptionInsertDTO dto = new SubscriptionInsertDTO(999L, 10L, PaymentMethod.CASH);

        when(memberRepository.findByIdAndDeletedFalse(999L)).thenReturn(Optional.empty());

        assertThatThrownBy(() -> subscriptionService.createSubscription(dto))
                .isInstanceOf(EntityNotFoundException.class);

        verifyNoInteractions(subscriptionPlanRepository);
        verifyNoInteractions(paymentRepository);
    }

    @Test
    void createSubscription_throwsNotFound_whenPlanDoesNotExist() {
        SubscriptionInsertDTO dto = new SubscriptionInsertDTO(1L, 999L, PaymentMethod.CASH);

        when(memberRepository.findByIdAndDeletedFalse(1L)).thenReturn(Optional.of(member));
        when(subscriptionPlanRepository.findById(999L)).thenReturn(Optional.empty());

        assertThatThrownBy(() -> subscriptionService.createSubscription(dto))
                .isInstanceOf(EntityNotFoundException.class);

        verifyNoInteractions(paymentRepository);
    }
}
